### ISSUE TITLE
SSL client zombie process issue

### ISSUE THREAD

**Issue by sagezhj** [blinko-space/blinko#403]
**Describe the bug**
在用 docker-compose 运行 blinko 后，使用正常，容器无错误日志，但宿主机出现了许多 ssl_client 僵尸进程。

**To Reproduce**
1. 复制docker-compose.yml内容，并修改，修改后文件已附后
2. docker compose up -d运行
3. 运行使用均无异常，容器日志也没有日常提示
4. 每次登录主机均提示多个僵尸进程，今天刚刚发现时有近300个僵尸进程，其中。经过PID检查，对应到blinko容器

**Expected behavior**
blinko容器进程无ssl_client僵尸进程.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: v0.32.11

**Additional context**
修改后compose.yaml文件
```
services:
  blinko:
    image: blinkospace/blinko:latest
    container_name: blinko
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: https://
      NEXT_PUBLIC_BASE_URL: https://
      NEXTAUTH_SECRET: 
      DATABASE_URL: postgresql://blinko:password@postgres:5432/blinko
    depends_on:
      postgres:
        condition: service_healthy
    # Make sure you have enough permissions.
    volumes:
       - ./data:/app/.blinko
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 8032:1111
    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:1111/"]
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "https://"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:latest
    container_name: blinko-postgres
    restart: always
    # ports:
    #   - 5435:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blinko
      POSTGRES_USER: blinko
      POSTGRES_PASSWORD: password
      TZ: Asia/Shanghai
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
```
ps -aux|grep Z报错信息：
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      215424  0.0  0.0      0     0 ?        Zs   13:28   0:00 [node] <defunct>
root      216023  0.0  0.0      0     0 ?        Z    13:28   0:00 [ssl_client] <defunct>
root      216531  0.0  0.0      0     0 ?        Z    13:29   0:00 [ssl_client] <defunct>
……（下午1点半启动，截至3点不到，已经180个僵尸进程了）
```
