### ISSUE TITLE
Network error when trying to update AI Models

### ISSUE THREAD

**Issue by Argee8989** [blinko-space/blinko#611]
**Describe the bug**
When I try to change the AI Model, the app displays a network error message

**To Reproduce**
1. Go to Settings
2. Activate AI
3. The dropdown is not populated
4. Refresh the Model (AI) dropdown and a network error shows up
5. See error
![Image](https://github.com/user-attachments/assets/db47553c-cf04-4ae2-96c0-434feb60989b)

6. **Expected behavior**
Once you change the Model Provider the Models should be updated

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Docker Install
 - Browser Opera, Vivaldi, Firefox

**Additional context**
Log files are clean --> No errors
Please see the docker compose file. Tried with my own domain but gave up and used the local url one to see if that was the problem:
```yaml
  networks:
    blinko-network:
      driver: bridge

  services:
    blinko-website:
      image: blinkospace/blinko:latest
      container_name: blinko-website
      environment:
        NODE_ENV: production
        NEXTAUTH_URL: http://localhost:1111
        # IMPORTANT: If you want to use sso, you must set NEXTAUTH_URL to your own domain
        NEXT_PUBLIC_BASE_URL: http://localhost:1111
        # IMPORTANT: Replace this with your own secure secret key!
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      depends_on:
        postgres:
          condition: service_healthy
      # Make sure you have enough permissions.
      volumes:
        - /opt/docker/stacks/blinko/data:/app/.blinko:rw
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      ports:
        - 1111:1111
      healthcheck:
        test: ["CMD", "curl", "-f", "http://blinko-website:1111/"]
        interval: 30s 
        timeout: 10s   
        retries: 5     
        start_period: 30s 
      networks:
        - blinko-network

    postgres:
      image: postgres:14
      container_name: blinko-postgres
      restart: always
      ports:
        - 5435:5432
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        TZ: Europe/Madrid
      # Persisting container data
      # Make sure you have enough permissions.
      volumes:
        - /opt/docker/stacks/blinko/db:/var/lib/postgresql/data:rw
      healthcheck:
        test:
          ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
        interval: 5s
        timeout: 10s
        retries: 5
      networks:
        - blinko-network
  ```
