### ISSUE TITLE
Error [LibsqlError]: SQLITE_ERROR: no such table: blinko

### ISSUE THREAD

**Issue by 503Dev** [blinko-space/blinko#646]
**Describe the bug**
The error occurs in logs when adding notes and other items. It also occurs in AI chat and breaks the functionality. This is on a fresh docker compose setup using the official bash setup script provided by blinko. 

The issue is clear that the table is missing. This is not a user setup error. Checking the DB schema we can see no blinko table is even being created:
https://github.com/blinko-space/blinko/blob/main/prisma/schema.prisma

It doesn't appear in any of the 22 migrations either. If it's never created how could it even function. 

**To Reproduce**
1. Go to AI chat
2. Attempt a query 
3. See error

**Expected behavior**
This should not occur especially on a fresh setup using the official provided docker compose. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 
 - Browser: Chrome
 - Release: latest tag

**Additional context**
Again, this is not user error. Looking in your prisma schema and migrations there is no declaration of a blinko table yet multiple functions reference it causing errors.

**Comment by 503Dev** [comment]
`Please import "createLogger" from "@mastra/core/logger" instead of "@mastra/core"
Error [LibsqlError]: SQLITE_ERROR: no such table: blinko
    at g (.next/server/chunks/6031.js:175:6656)
    at h (.next/server/chunks/6031.js:175:5831)
    at f.execute (.next/server/chunks/6031.js:175:4088)
    at d.upsert (.next/server/chunks/6031.js:149:19)
    at async A.embeddingUpsert (.next/server/chunks/6031.js:227:12421) {
  code: 'SQLITE_ERROR',
  rawCode: 1,
  [cause]: SqliteError: no such table: blinko
      at h (.next/server/chunks/6031.js:175:4879)
      at f.execute (.next/server/chunks/6031.js:175:4088)
      at d.upsert (.next/server/chunks/6031.js:149:19)
      at async A.embeddingUpsert (.next/server/chunks/6031.js:227:12421) {
    code: 'SQLITE_ERROR',
    rawCode: 1
  }
} embeddingUpsert error
undefined customPrompt
Please import "createLogger" from "@mastra/core/logger" instead of "@mastra/core"
prisma:error
Invalid `prisma.tagsToNote.create()` invocation:


Unique constraint failed on the fields: (`noteId`,`tagId`)
Error [LibsqlError]: SQLITE_ERROR: no such table: blinko
    at g (.next/server/chunks/6031.js:175:6656)
    at h (.next/server/chunks/6031.js:175:5831)
    at f.execute (.next/server/chunks/6031.js:175:4088)
    at d.upsert (.next/server/chunks/6031.js:149:19)
    at async A.embeddingUpsert (.next/server/chunks/6031.js:227:12421) {
  code: 'SQLITE_ERROR',
  rawCode: 1,
  [cause]: SqliteError: no such table: blinko
      at h (.next/server/chunks/6031.js:175:4879)
      at f.execute (.next/server/chunks/6031.js:175:4088)
      at d.upsert (.next/server/chunks/6031.js:149:19)
      at async A.embeddingUpsert (.next/server/chunks/6031.js:227:12421) {
    code: 'SQLITE_ERROR',
    rawCode: 1
  }
} embeddingUpsert error`

**Comment by b3ar1nth3w00ds** [comment]
Confirmed, same here.

**Comment by DC959** [comment]
I seemed to resolve this by simply making sure that my local ai instance can talk to both blinko and postgres.

I originally had the postgres container and blinko on a separate docker network that we can call blinko-network and then a separate network connecting blinko to my local ai instance running on koboldcpp which we can call frontend, I have internal dns routing to a url for blinko and for my kobold instance with signed certs.

Getting rid of blinko-network and putting the postgres, blinko and kobolcpp containers all on the same frontend network, making sure that all have the dns: variable set to my local dns resolver so they all know how to route to each other seemed to resolve this, I no longer get the blinko table error and I am able to use the ai functionality.

**Comment by joaoofreitas** [comment]
> I seemed to resolve this by simply making sure that my local ai instance can talk to both blinko and postgres.
> 
> I originally had the postgres container and blinko on a separate docker network that we can call blinko-network and then a separate network connecting blinko to my local ai instance running on koboldcpp which we can call frontend, I have internal dns routing to a url for blinko and for my kobold instance with signed certs.
> 
> Getting rid of blinko-network and putting the postgres, blinko and kobolcpp containers all on the same frontend network, making sure that all have the dns: variable set to my local dns resolver so they all know how to route to each other seemed to resolve this, I no longer get the blinko table error and I am able to use the ai functionality.

@DC959 Can you provide an example with your docker-compose?

**Comment by BaseMax** [comment]
same here.

<img width="1550" height="901" alt="Image" src="https://github.com/user-attachments/assets/916f00d3-2068-4c2a-be62-f5f4a105b3a7" />

**Comment by BaseMax** [comment]
My current version:

<img width="643" height="236" alt="Image" src="https://github.com/user-attachments/assets/e44173b1-dfe8-4734-ac62-50c15d6853d1" />

**Comment by DC959** [comment]
Here's my compose.yaml for Blinko
```
version: "3.8"
services:
  blinko-website:
    restart: unless-stopped
    image: blinkospace/blinko:1.2.2
    container_name: blinko-website
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: https://domain.name
      NEXT_PUBLIC_BASE_URL: domain.name
      NEXTAUTH_SECRET: ${NEXT_AUTH}
      DATABASE_URL: postgresql://blinko:${PG_PASS}@postgres:5432/blinko
    depends_on:
      postgres:
        condition: service_healthy
      # Make sure you have enough permissions.
    volumes:
      - /data/blinko/app:/app/.blinko
    logging:
      options:
        max-size: 10m
        max-file: "3"
        #healthcheck:
        #test:
        #- CMD
        #- curl
        #- -f
        #- http://blinko-website:1111/
        #interval: 30s
        #timeout: 10s
        #retries: 5
        #start_period: 30s
    env_file:
      - .env
    networks:
      - frontend
  postgres:
    restart: unless-stopped
    image: postgres:14
    container_name: blinko-postgres
    environment:
      POSTGRES_DB: blinko
      POSTGRES_USER: blinko
      POSTGRES_PASSWORD: ${PG_PASS}
      TZ: Pacific/Auckland
      # Persisting container data
      # Make sure you have enough permissions.
    volumes:
      - /data/blinko/postgres/:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - blinko
        - -d
        - blinko
      interval: 5s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    networks:
      - frontend
networks:
  frontend:
    external: true
```

And here's my compose.yaml for koboldcpp which I use to host my local model
```
version: "3.8"
services:
  koboldcpp:
    container_name: koboldcpp
    restart: unless-stopped
    image: koboldai/koboldcpp:latest
    ports: []
    networks:
      - frontend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    environment:
      KCPP_ARGS: --usecublas --gpulayers 999 --contextsize 32768 --overridetensors
        ".ffn_.*_exps.=CPU" --multiuser --flashattention --model
        Qwen3-30B-A3B-UD-Q4_K_XL.gguf --embeddingsmodel
        granite-embedding-278m-multilingual-Q8_0.gguf --defaultgenamt 2048
    volumes:
      - /data/koboldcpp/models:/opt/koboldcpp/
networks:
  frontend:
    external: true
```

As you can note, all containers are connected to the same external docker network called frontend, this seems to be key to resolving the issue.

Previously when I was experiencing this issue, I had the blinko container connected to the external frontend network so it could communicate with koboldcpp and also an internal network to the docker stack called blinko-network, postgres was then only connected to this blinko-network, my intention being that blinko and koboldcpp needed to communicate, so having them both on frontend made sense, but koboldcpp didn't need to communicate with postgres, only blinko needed to, this resulted in the error you all seem to be seeing, simply placing koboldcpp (or your preferred tool), blinko and the postgres containers all on the same external network, resolved the issue.

Hopefully that all makes sense.
