### ISSUE TITLE
AI doesn't respond back

### ISSUE THREAD

**Issue by igor-hara** [blinko-space/blinko#713]
**Describe the bug**
Hello,
I'm trying to add **ollama** with Blinko app.
Did same steps to add models like here: [DEV](https://dev.to/blacknight318/setup-blinko-notes-with-ollama-5h7)

**my compose file**:
```yaml
networks:
  blinko-network:
    driver: bridge
    name: blinko-network

volumes:
  ollama-data:

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-data:/root/.ollama
    networks:
      - blinko-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:11434/api/tags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  blinko-website:
    image: blinkospace/blinko:latest
    container_name: blinko-website
    environment:
      NODE_ENV: production
      NEXTAUTH_SECRET: 9QluSyUzuRgb3YnQ=
      DATABASE_URL: postgresql://postgres:postgress@postgres:5432/postgres
      AI_API_URL: http://ollama:11434
      NEXTAUTH_URL: https://blinko.domains.org  
      NEXT_PUBLIC_BASE_URL: https://blinko.domains.org
    depends_on:
      - postgres
      - ollama
    volumes:
      - ./app:/app/.blinko
    ports:
      - 1111:1111
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1111"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - blinko-network
    restart: unless-stopped  

  postgres:
    image: postgres:14
    container_name: blinko-postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgress
      TZ: Europe/Zagreb
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - blinko-network
```

**To Reproduce**

![Image](https://github.com/user-attachments/assets/95c9eed0-a0bb-4222-a581-c71d4d166f96)

- Checking Endpoint url:

![Image](https://github.com/user-attachments/assets/0293c277-a594-4216-b07a-93da65ba5610)

- Inside AI page, type any text
After some 'loading' - no response

**Expected behavior**
Should return some response

**Screenshots**

**Desktop (please complete the following information):**
- Ugreen NAS
